apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/helloaman0508/java-prototype-gitops-argocd.git' # Replace with your repo URL
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: spring-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true